name: GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  metrics:
    permissions:
      contents: write   # ðŸ”¥ THIS LINE IS REQUIRED
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          user: YUG3011
          template: classic
          base: header, activity, community, repositories
          languages: yes
          languages.limit: 10
          languages.details: percentage
          config.timezone: Asia/Kolkata
